/**
 * companies.js — Empresas en el CV de Nadia Zurita
 */

export const COMPANIES = [
  {
    id:      'afp-capital',
    slug:    'afp-capital',
    name:    'AFP Capital',
    period:  'Oct 2024 – Mar 2026',
    description: 'AFP Capital se separó del grupo Sura y, con eso, perdió acceso a toda la infraestructura de datos compartida. La compañía quedó sin plataforma propia. Apoyé la construcción desde cero del nuevo ecosistema de datos en GCP, alineada con los distintos departamentos que se iban formando ( Arquitectura, Gobierno de Datos, QA) desarrollando pipelines de ingesta, arquitectura Data Lakehouse en BigQuery, automatización serverless y gobierno de datos, todo en un entorno regulado por la CMF',
    role:    'Senior Data Engineer',
    location: 'Remote',
    achievements: [
      'Implementación de arquitectura Data Lakehouse de 3 capas en GCP',
      'Migración de datos maestros a través de Cloud Data Fusion',
      'Creación, levantamiento y desarrollo de procesos de datos para la visualización de Power BI (Base maestra, equipo responsable, saldos, carterización de clientes, promesa de contacto, base asesoría)',
      'Generación de POC de Dataplex para gobierno y linaje de datos',
      'Levantamiento, implementación y desarrollo de proyecto del nuevo informe previsional',
      'Desarrollo de proyecto de canal responsable para la asignación de ejecutivo a cliente',
    ],
    technologies: ['BigQuery', 'Cloud Data Fusion', 'Dataform', 'Dataproc', 'Dataplex', 'PySpark','Dataflow', 'Cloud Functions', 'Terraform', 'Python', 'SQL','Cloud Run', 'Cloud Functions', 'Cloud Storage', 'Dataproc', 'Pub/Sub', 'Cloud Scheduler', 'Dataplex', 'IAM'],
    projects: [
      {
        id: 'afp-migracion-end-to-end',
        name: 'Migración End-to-End On-Premise → GCP',
        description: 'Migración de datos desde bases de datos on-premise hacia infraestructura en GCP con validación de integridad y zero-downtime.',
        stack: [
          'Google Cloud Storage: Gestión de archivos en buckets para entornos ETL, con control de versiones y organización por ambientes (dev, qa, prod).',
          'BigQuery: Modelado de datos, creación de vistas y tablas particionadas, optimización de consultas y manejo de grandes volúmenes de datos.',
          'Cloud Data Fusion: Pipelines de ingesta y transformación desde orígenes on-premise y cloud hacia BigQuery con validación de esquemas.',
          'Cloud Dataflow: Procesamiento batch y streaming de datos con integración con Pub/Sub para ingestas de tiempo real.',
          'Cloud Functions: Funciones serverless para transformación y validación de datos en tiempo real durante la migración.',
          'Terraform: Infraestructura como código para provisionar recursos (BigQuery, Storage, cuentas de servicio, permisos IAM).',
          'Python: Scripts de migración y validación de integridad de datos.',
          'SQL: Queries de validación y reconciliación entre origen y destino.',
        ],
      },
      {
        id: 'afp-arquitectura-datos',
        name: 'Apoyo en Arquitectura de Datos',
        description: 'Diseño y evolución de la arquitectura Data Lakehouse con capas crudo, curado y producto para soportar múltiples casos de uso analíticos.',
        stack: [
          'BigQuery: Diseño de esquema dimensional, tablas de hechos y dimensiones, optimización para análisis OLAP.',
          'Dataform: Modelado modular en SQL, estructuración en capas (raw, staging, marts), control de dependencias y versionamiento con Git.',
          'Google Cloud Storage: Diseño de estructura de buckets por ambiente, retención y ciclo de vida de datos, optimización de costos.',
          'Identity and Access Management (IAM): Configuración de políticas de acceso granulares por rol y ambiente.',
          'Cloud Resource Manager: Gestión de proyectos, permisos y presupuestos de GCP.',
          'Monitoring y Logging: Implementación de alertas y dashboards de salud de la infraestructura de datos.',
        ],
      },
      {
        id: 'afp-dataform',
        name: 'Desarrollo de Dataform',
        description: '80+ modelos SQL documentados con dependencias explícitas, versionado en Git, y ejecución automática con testing integrado.',
        stack: [
          'Dataform: Desarrollo modular con SQL, definición de dependencias (ref/source), testing y documentación de columnas.',
          'Git & GitHub: Versionado de modelos, code reviews, branching strategy (main/dev), CI/CD integration.',
          'BigQuery: Compilación de SQL, ejecución de queries, optimización de performance con particionado y clustering.',
          'dbt concepts: Aunque usa Dataform, aplicación de buenas prácticas de dbt (modelado en capas, testing, documentación).',
          'YAML: Definición de configuraciones y metadatos de modelos en Dataform.',
        ],
      },
      {
        id: 'afp-consultas-programadas',
        name: 'Desarrollo de Consultas Programadas',
        description: 'Implementación de queries programadas (scheduled queries) para agregaciones diarias, actualizaciones de vistas y generación de reportes automatizados.',
        stack: [
          'BigQuery: Desarrollo y optimización de SQL complejas con window functions, subconsultas correlacionadas y CTEs.',
          'Scheduled Queries: Configuración de jobs que ejecutan automáticamente a intervalos específicos con notificaciones de error.',
          'SQL: Query optimization, índices, particionado y clustering para mejorar performance.',
          'Python: Scripts de Post-processing para transformar resultados y enviar a sistemas downstream.',
          'Cloud Pub/Sub: Integración de queries programadas con eventos de tiempo real.',
        ],
      },
      {
        id: 'afp-cloud-functions-run',
        name: 'Desarrollo de Cloud Functions & Cloud Run',
        description: 'Dos patrones complementarios de Cloud Functions en producción: pipeline batch programado para migración de fuentes on-premise y pipeline event-driven para carga de archivos con validación en tres capas, ambos con notificaciones automáticas vía SendGrid.',
        diagrams: [
          {
            id: 'cf-migracion-fuentes',
            title: 'Migración de Fuentes On-Premise con Cloud Functions',
            image: '/projects/cloud-functions-run/migracion-cf.png',
            description: 'Flujo programado diario/mensual que extrae datos desde Oracle, SQL Server y MySQL, los ingesta vía Cloud Data Fusion y aplica lógica de negocio en Cloud Functions antes de escribir en BigQuery para consumo en PowerBI y Looker.',
            steps: [
              {
                label: 'Extracción',
                detail: 'Cloud Data Fusion conecta las tres fuentes on-premise (Oracle BD, SQL Server, MySQL) y carga los datos crudos en BigQuery organizados en capas Crudo / Curado / Producto.',
              },
              {
                label: 'Orquestación',
                detail: 'Cloud Scheduler dispara las Cloud Functions según ventanas diarias y mensuales alineadas con los calendarios de corte de AFP Capital.',
              },
              {
                label: 'Lógica de negocio',
                detail: 'Cloud Functions aplica transformaciones, enriquecimiento y reglas de negocio AFP antes de entregar al procesamiento SQL final en BigQuery.',
              },
              {
                label: 'Notificaciones',
                detail: 'SendGrid envía alertas automáticas de éxito o fallo a los equipos responsables al finalizar cada carga, con detalle de registros procesados.',
              },
              {
                label: 'Consumo',
                detail: 'Los modelos certificados en BigQuery alimentan dashboards de reportería en PowerBI y Looker para los equipos de negocio.',
              },
            ],
          },
          {
            id: 'cf-carga-archivo',
            title: 'Carga de Archivo por Evento — GCS → BigQuery',
            image: '/projects/cloud-functions-run/migracion-archivo.png',
            description: 'Pipeline event-driven que se activa al detectar un archivo nuevo en Cloud Storage, ejecuta validación secuencial en tres capas dentro de la Cloud Function y finaliza con carga a BigQuery o rechazo detallado según resultado.',
            steps: [
              {
                label: 'Trigger',
                detail: 'La llegada de un archivo al bucket GCS genera un evento objeto que dispara la Cloud Function de forma automática e inmediata, sin polling.',
              },
              {
                label: 'Capa 1 — Formato y esquema',
                detail: 'Verifica que el archivo respete la estructura esperada: columnas requeridas, encoding correcto y formato de cabeceras.',
              },
              {
                label: 'Capa 2 — Tipos y nulos',
                detail: 'Controla que los tipos de dato sean los declarados y que los campos obligatorios no vengan vacíos o con valores nulos.',
              },
              {
                label: 'Capa 3 — Reglas de negocio',
                detail: 'Aplica validaciones de dominio AFP: rangos de montos válidos, RUT bien formado y fechas dentro del período de proceso vigente.',
              },
              {
                label: 'Rechazo',
                detail: 'Si falla cualquier capa: el archivo se mueve al Bucket de Fallos para auditoría y SendGrid envía un email con el detalle exacto del error.',
              },
              {
                label: 'Carga exitosa',
                detail: 'Si pasa las tres capas: inserción en la tabla BigQuery correspondiente y email de confirmación al equipo con el conteo de registros cargados.',
              },
            ],
          },
        ],
        stack: [
          'Cloud Functions: Funciones serverless en Python para ETL triggers, transformaciones de datos y validaciones en tres capas (formato, tipos, reglas de negocio).',
          'Cloud Run: Contenedores Docker con endpoints REST para microservicios de data processing con escalado automático según demanda.',
          'Cloud Data Fusion: Pipelines de ingesta desde Oracle, SQL Server y MySQL hacia BigQuery con control de esquemas y transformaciones visuales.',
          'Cloud Scheduler: Orquestación de disparos diarios y mensuales de Cloud Functions según calendarios de corte AFP.',
          'Cloud Storage: Bucket de entrada para archivos y bucket de fallos para archivos rechazados, con eventos objeto como triggers.',
          'BigQuery: Destino final de los datos procesados, organizado en capas Crudo/Curado/Producto con procesamiento SQL post-carga.',
          'SendGrid: Notificaciones automáticas de éxito, fallo y detalle de rechazo a los equipos responsables tras cada ejecución.',
          'Python: Lógica de negocio, librerías google-cloud-bigquery, pandas y sendgrid para transformación, validación y notificación.',
          'IAM & Service Accounts: Autenticación y autorización granular para el acceso de Cloud Functions a BigQuery y Cloud Storage.',
        ],
      },
      {
        id: 'afp-gobierno-datos-dataplex',
        name: 'Gobierno de Datos con Dataplex',
        description: 'Diseño e implementación de arquitectura de gobierno de datos en tres capas usando Dataplex como plataforma central, con tagging automático, reglas de calidad SQL, seguridad column-level y publicación de SLAs en Looker Studio.',
        image: '/projects/gobierno-datos-dataplex/arquitectura-dataplex.png',
        architecture: {
          layers: [
            {
              name: 'Capa Crudo',
              color: 'amber',
              description: 'Recibe los datos tal cual desde Oracle y SQL Server vía Cloud Data Fusion. Dataplex aplica tagging y linaje automático desde el minuto uno.',
            },
            {
              name: 'Capa Curada',
              color: 'purple',
              description: 'Contiene toda la lógica de Data Quality: reglas SQL que validan nulos, duplicados, formatos erróneos y anomalías antes de promover el dato.',
            },
            {
              name: 'Capa Productiva',
              color: 'teal',
              description: 'Modelos certificados con IAM granular — column-level security y row-level filters para los datos sensibles de afiliados.',
            },
          ],
          realCase: 'Flujo de cotizaciones AFP: cada noche los datos de ~2M afiliados se extraen desde Oracle a GCS, pasan por reglas de Dataplex, se transforman con Dataform en BigQuery, se aplican políticas IAM por segmento y se publican los SLAs de calidad en Looker Studio. Reglas específicas: validación de RUT, monto mayor a cero, fecha dentro del período vigente y unicidad por afiliado/mes.',
          crossCuttingTools: ['Terraform (IaC para políticas Dataplex)', 'GitLab (control de versiones)', 'Cloud Scheduler (jobs nocturnos)', 'Cloud Composer / Airflow (orquestación de DAGs)'],
        },
        stack: [
          'Dataplex Lake: Contenedor con tres zonas delimitadas (Crudo, Curada, Productiva), tagging automático y linaje de assets desde ingesta.',
          'Cloud Data Fusion: Pipelines de ingesta desde Oracle y SQL Server hacia la capa Crudo en GCS.',
          'Data Quality Rules: Reglas SQL en Dataplex para validar nulos, duplicados, formatos erróneos y anomalías entre capas.',
          'Dataform: Transformación y modelado en BigQuery con dependencias explícitas entre capas curada y productiva.',
          'IAM (column-level & row-level): Políticas granulares sobre datos sensibles de afiliados — filtros por columna y por fila según segmento.',
          'Looker Studio: Dashboards de monitoreo de SLAs de calidad de datos en tiempo real.',
          'Terraform: IaC para provisionar y versionar las políticas de Dataplex, zonas y assets como código.',
          'Cloud Composer / Airflow: Orquestación de DAGs nocturnos para el flujo completo de cotizaciones.',
          'Cloud Scheduler: Triggers de jobs nocturnos de extracción y validación.',
          'GitLab: Control de versiones de reglas de calidad, configuraciones de Dataplex y DAGs.',
        ],
      },
      {
        id: 'afp-poc-generador-metadata',
        name: 'POC Generador de Metadata con IA',
        description: 'Prototipo de generación automática de metadata de negocio para las tablas migradas desde Oracle, combinando el esquema real, datos de muestra y documentación regulatoria para producir descripciones, clasificación PII y alertas de calidad sin intervención manual.',
        image: '/projects/poc_metadata/poc_metadata.png',
        realCase: {
          inputs: [
            'Esquema de tabla_cotizaciones: 127 columnas migradas desde Oracle, con nombres técnicos heredados del sistema legacy.',
            '50 filas de muestra del último trimestre: datos reales anonimizados para que el modelo detecte patrones y anomalías.',
            'Documentación regulatoria indexada: D.L. 3.500 y Circulares CMF/SVS vectorizadas para contextualizar cada campo con su obligación normativa.',
          ],
          outputs: [
            'Descripciones de negocio en español: definición de cada columna en lenguaje entendible para el equipo de negocio, sin tecnicismos de Oracle.',
            'Clasificación PII columna por columna: identifica automáticamente RUT, montos, cuentas y datos sensibles según la regulación vigente.',
            'Dominio por tabla: asigna a qué área de negocio pertenece cada tabla (Recaudación, Afiliados, Inversiones, etc.).',
            'Alertas de anomalías: detecta en la muestra valores que romperían pipelines — como los nulos encontrados en cuota_historica antes de que llegaran a producción.',
          ],
        },
        stack: [
          'Vertex AI / Gemini: Modelo de lenguaje para generar descripciones de columnas y clasificar PII a partir del esquema y documentación regulatoria.',
          'BigQuery: Fuente del esquema real (INFORMATION_SCHEMA) y extracción de muestras representativas para análisis.',
          'Cloud Storage: Almacenamiento de documentos regulatorios (D.L. 3.500, Circulares CMF/SVS) indexados para RAG.',
          'Dataplex Data Catalog: Destino de la metadata generada — tags de negocio, clasificación de sensibilidad y dominio por asset.',
          'Python: Orquestación del pipeline: extracción de esquema, llamadas a la API del modelo, validación y escritura en el catálogo.',
          'Cloud Functions: Trigger serverless para ejecutar el generador cuando se detecta una nueva tabla o cambio de esquema.',
          'RAG (Retrieval-Augmented Generation): Recuperación de fragmentos relevantes de la normativa para fundamentar cada descripción generada.',
        ],
      },
    ],
  },

  {
    id:      'elitsoft',
    slug:    'elitsoft',
    name:    'ElitSoft',
    period:  'Abr 2023 – Sep 2024',
    description: 'Orquestación de pipelines AWS con Apache Airflow y arquitectura de CI/CD para data.',
    role:    'Data Engineer',
    location: 'Remote',
    achievements: [
      'Automatización del 100% de ingestas batch desde legacy a Redshift',
      'Reducción del 60% en tiempo de procesamiento con Spark en EMR',
      'Implementación de CI/CD con AWS CodePipeline y Jenkins',
      'Cero intervenciones manuales en producción por 6 meses consecutivos',
    ],
    technologies: ['AWS Glue', 'Amazon EMR', 'Apache Airflow', 'Redshift', 'Lambda', 'CodePipeline'],
    projects: [
      {
        id: 'elitsoft-automatizacion-ingestas',
        name: 'Automatización de Ingestas Batch Legacy → Redshift',
        description: 'Automatización del 100% de ingestas batch desde sistemas legacy a Redshift mediante DAGs en Airflow con validación de integridad y monitoreo.',
        stack: [
          'AWS Glue: Catálogo de datos, descubrimiento de esquemas, transformación ETL serverless para ingestas desde múltiples orígenes.',
          'Apache Airflow: Orquestación de DAGs para scheduling de ingestas, manejo de dependencias, reintentos y alertas de fallos.',
          'Redshift: Data warehouse, materialización de tablas, optimización con distkeys y sortkeys, gestión de concurrencia.',
          'AWS Lambda: Funciones serverless para transformaciones ligeras, validación de datos y notificaciones.',
          'S3: Almacenamiento intermedio de archivos, staging tables para ingestas incrementales.',
          'CloudWatch: Monitoreo de jobs, logs centralizados, alertas y dashboards de performance.',
          'Python: Desarrollo de DAGs, custom operators, transformaciones de datos, validaciones.',
          'SQL: Queries de transformación, reconciliación entre origen y destino, agregaciones finales.',
        ],
      },
      {
        id: 'elitsoft-spark-emr',
        name: 'Optimización de Spark en Amazon EMR',
        description: 'Reducción del 60% en tiempo de procesamiento mediante tuning de configuraciones de Spark, particionado de datos y optimización de memoria.',
        stack: [
          'Amazon EMR: Cluster management, versioning de Spark, configuración de executors y drivers para máximo performance.',
          'Apache Spark: Optimización de stage execution, lazy evaluation, particionado de DataFrames, cache strategies.',
          'PySpark: Desarrollo de jobs de transformación con optimizaciones de performance (broadcast joins, columnar storage).',
          'S3: Lectura/escritura optimizada, particionado de datos por fecha/región para scan reduction.',
          'YARN: Resource management, memory allocation, job scheduling y monitoring.',
          'CloudWatch: Metrics de cluster, CPU/Memory utilization, job duration tracking.',
          'SQL: Queries distribuidas en Spark SQL, predicate pushdown, columnar formats (Parquet).',
        ],
      },
      {
        id: 'elitsoft-cicd-pipeline',
        name: 'CI/CD Pipeline con AWS CodePipeline y Jenkins',
        description: 'Implementación de pipeline end-to-end para automatización de builds, tests y deployments de código de data en múltiples ambientes.',
        stack: [
          'AWS CodePipeline: Orquestación de stages (source, build, test, deploy), integración con Git, manual approvals.',
          'Jenkins: Ejecución de builds, tests unitarios, código estático, deployment a ambientes (dev, qa, prod).',
          'AWS CodeBuild: Compilación y testing de código Python, instalación de dependencias, unit tests.',
          'GitHub/GitLab: Repositorio de código, webhooks para trigger de pipelines, pull request reviews.',
          'Docker: Containerización de DAGs y jobs Spark para reproducibilidad en distintos ambientes.',
          'Terraform: IaC para provisionar infraestructura (clusters, jobs, buckets) desde código.',
          'pytest: Framework de testing para validar lógica de transformación de datos.',
          'CloudFormation: Declaración de infraestructura como código para ambientes de dev/qa/prod.',
        ],
      },
      {
        id: 'elitsoft-dags-airflow',
        name: 'Desarrollo de DAGs Orchestración en Airflow',
        description: 'Diseño de DAGs resilientes con manejo de errores, reintentos inteligentes, y monitoreo centralizado para 50+ pipelines diarios.',
        stack: [
          'Apache Airflow: DAG definitions, custom operators, sensors, XComs para comunicación entre tareas, SLA policies.',
          'Python: Desarrollo de DAGs, custom hooks y operators, lógica de transformación, error handling.',
          'AWS Airflow Managed Workflows: Managed service con auto-scaling, monitoring integrado, seguridad enterprise.',
          'Redshift: Conexiones de destino, inserción de datos, queries de validación post-ingesta.',
          'S3: Staging de archivos, logging de ejecuciones, backups de metadatos.',
          'Email/Slack: Notificaciones de fallo, alertas de SLA breaches, reportes diarios.',
          'SQL: Queries de transformación ejecutadas dentro de DAGs, validación de datos.',
        ],
      },
      {
        id: 'elitsoft-infraestructura-aws',
        name: 'Infraestructura AWS para Data Pipelines',
        description: 'Diseño de arquitectura serverless y escalable para pipelines de datos con alta disponibilidad, disaster recovery y optimización de costos.',
        stack: [
          'Terraform: IaC para provisionar Redshift, Glue, Airflow, EMR, IAM roles, security groups y VPCs.',
          'AWS VPC: Configuración de subnets, security groups, endpoints para acceso privado a servicios.',
          'IAM: Gestión de roles y políticas granulares para cada componente (Glue, Airflow, Lambda).',
          'CloudWatch: Monitoreo centralizado, logs, métricas, dashboards y alarmas customizadas.',
          'AWS Secrets Manager: Gestión segura de credenciales de bases de datos y APIs.',
          'AWS S3: Bucket policies, versioning, lifecycle rules, encryption at rest y in transit.',
          'AWS Backup: Snapshots automáticos de Redshift, replicación a otra región para DR.',
        ],
      },
    ],
  },

  {
    id:      'cic-sa',
    slug:    'cic-sa',
    name:    'CIC S.A.',
    period:  'Mar 2020 – Abr 2023',
    description: 'BI Developer / Data Analyst responsable del levantamiento del área de Business Intelligence de la empresa desde cero. Gestioné el presupuesto del área, el levantamiento de proyectos con gerencias y áreas de negocio (transporte, ventas, RRHH, comercial y finanzas) y la construcción de una plataforma analítica completa con QlikView, Qlik Sense y NPrinting. Lideré la implementación del área de QA de datos, estableciendo estándares de pruebas y validación previos a la ingesta de información. Ejecuté una POC de migración a GCP integrando fuentes Oracle, SQL Server, PostgreSQL y archivos de texto plano, sentando las bases para una arquitectura cloud-native.',
    role:    'BI Developer / Data Analyst',
    location: 'Presencial - Santiago',
    achievements: [
      'Creación del área de Business Intelligence de la empresa desde cero: definición de procesos, herramientas y equipo',
      'Gestión de presupuesto del área y levantamiento de proyectos con gerencias de transporte, ventas, RRHH, comercial y finanzas',
      'Liderazgo del área de QA de datos: estandarización de pruebas y validaciones previas a ingesta en el Data Warehouse',
      'POC de migración a GCP integrando fuentes Oracle, SQL Server, PostgreSQL y archivos de texto plano',
      'Dashboard logístico en tiempo real (actualización cada 15 min) con adopción del 100% del área',
      'Reducción del tiempo de reporte de 2 días a tiempo real mediante automatización ETL con Control-M y Oracle',
      'Migración de aplicaciones legacy QlikView a Qlik Sense con mejora de experiencia de usuario',
    ],
    technologies: ['Qlik Sense', 'QlikView', 'NPrinting', 'Oracle', 'SQL Server', 'PostgreSQL', 'Control-M', 'SQL', 'Python', 'GCP', 'dbt', 'BigQuery'],
    projects: [
      {
        id: 'cic-dashboard-logistico',
        name: 'Dashboard Logístico Real-Time en Qlik Sense',
        description: 'Dashboard interactivo con actualización cada 15 minutos mostrando KPIs de logística, inventario y despachos con drilldown a nivel de detalle de transacciones.',
        compact: true,
        tags: ['Qlik Sense', 'Oracle', 'Control-M', 'NPrinting', 'SQL'],
        stack: [],
      },
      {
        id: 'cic-migracion-qlikview-sense',
        name: 'Migración de QlikView a Qlik Sense',
        description: 'Migración de aplicaciones legacy QlikView a Qlik Sense manteniendo funcionalidad y mejorando experiencia de usuario, con reescritura de scripts y nuevos templates de reportería.',
        compact: true,
        tags: ['QlikView', 'Qlik Sense', 'Qlik Script', 'NPrinting', 'Oracle SQL'],
        stack: [],
      },
      {
        id: 'cic-automatizacion-reportes',
        name: 'Automatización de Reportes con NPrinting',
        description: 'Sistema de generación y distribución automática de reportes en PDF, Excel y email hacia más de 50 usuarios ejecutivos diarios con scheduling y alertas.',
        compact: true,
        tags: ['NPrinting', 'Qlik Sense', 'Control-M', 'SQL', 'SharePoint'],
        stack: [],
      },
      {
        id: 'cic-etl-oracle-controlm',
        name: 'ETL Automatizado Oracle + Control-M',
        description: 'Pipeline ETL completo que ingesta datos desde múltiples tablas Oracle, aplica transformaciones de negocio y carga en el Data Warehouse de Qlik cada 6 horas.',
        compact: true,
        tags: ['Control-M', 'Oracle', 'SQL', 'Python', 'Qlik Script'],
        stack: [],
      },
      {
        id: 'cic-qa-datos',
        name: 'Área de QA de Datos',
        description: 'Creación y liderazgo del área de calidad de datos: definición de estándares de pruebas, validación de integridad y consistencia previas a ingesta, y automatización de pruebas para el Data Warehouse.',
        compact: true,
        tags: ['SQL', 'Python', 'Oracle', 'Control-M', 'Documentación técnica'],
        stack: [],
      },
      {
        id: 'cic-poc-gcp',
        name: 'POC Migración a GCP',
        description: 'Prueba de concepto para migración cloud integrando fuentes Oracle, SQL Server, PostgreSQL y archivos de texto plano hacia GCP, evaluando BigQuery como destino analítico y dbt para transformaciones.',
        compact: true,
        tags: ['GCP', 'BigQuery', 'Oracle', 'SQL Server', 'PostgreSQL', 'dbt'],
        stack: [],
      },
      {
        id: 'cic-kpis-comerciales',
        name: 'KPIs Comerciales y Operacionales',
        description: 'Dashboards con KPIs clave para las áreas comerciales y operacionales, con visualizaciones interactivas, filtros asociativos y plan de mejora continua sobre las aplicaciones existentes.',
        compact: true,
        tags: ['Qlik Sense', 'Oracle', 'SQL', 'Qlik Script', 'Control-M'],
        stack: [],
      },
      {
        id: 'cic-documentacion',
        name: 'Documentación y Entendimiento de Proyectos',
        description: 'Levantamiento y documentación de flujos de datos, diccionarios de datos, manuales de usuario y especificaciones técnicas de proyectos BI, asegurando trazabilidad y transferencia de conocimiento.',
        compact: true,
        tags: ['Documentación técnica', 'Diccionario de datos', 'Qlik Sense', 'ETL', 'Scrum'],
        stack: [],
      },
      {
        id: 'cic-panel-indicadores',
        name: 'Panel de Control e Indicadores Comerciales',
        description: 'Aplicaciones QlikView y Qlik Sense con panel de control corporativo, segmentación de clientes, indicadores comerciales, cuadraturas de ventas y estados de resultado para las distintas gerencias.',
        compact: true,
        tags: ['QlikView', 'Qlik Sense', 'SQL', 'Qlik Script', 'Scrum'],
        stack: [],
      },
      {
        id: 'cic-proyecciones-ventas',
        name: 'Proyecciones de Ventas, Stock y Control de Presupuesto',
        description: 'Scripts Python para generación de proyecciones de ventas, análisis de presupuesto por área y control de stock, automatizando el análisis de tendencias para la toma de decisiones gerenciales.',
        compact: true,
        tags: ['Python', 'Pandas', 'SQL Server', 'Excel', 'Oracle'],
        stack: [],
      },
    ],
  },

  {
    id:      'global-frozen',
    slug:    'global-frozen',
    name:    'Global Frozen',
    period:  'Oct 2019 – Mar 2020',
    description: 'Analista Qlik Sense en empresa del sector de alimentos, responsable del desarrollo y gestión de plataformas de datos para las áreas comerciales y operacionales. Implementé soluciones de inteligencia de negocios orientadas al control de cobranza, seguimiento de clientes con facturas a 30, 60 y 90 días, gestión de morosidad y un modelo de scoring para evaluar la viabilidad de crédito por cliente. El trabajo combinó análisis de datos, visualización en Qlik Sense y levantamiento directo de requerimientos con cada área.',
    role:    'Analista Qlik Sense',
    location: 'Presencial - Santiago',
    achievements: [
      'Desarrollo de solución de gestión de cobranza con seguimiento de clientes por tramos de 30, 60 y 90 días de facturación',
      'Implementación de modelo de scoring por cliente para evaluar viabilidad de crédito y riesgo de mora',
      'Identificación y gestión de clientes con atrasos para mejorar el cumplimiento de plazos de pago',
      'Análisis y generación de KPIs comerciales y operacionales en Qlik Sense',
      'Elaboración de plan de mejora continua para aplicaciones Qlik Sense nuevas y existentes',
      'Levantamiento de requerimientos y entrega de soluciones con distintas áreas de la empresa',
    ],
    technologies: ['Qlik Sense', 'MySQL', 'SQL', 'ETL', 'Qlik Script', 'Scoring'],
    projects: [
      {
        id: 'gf-cobranza-scoring',
        name: 'Gestión de Cobranza y Scoring de Clientes',
        description: 'Dashboard de cobranza con segmentación de clientes por tramos de facturación (30, 60 y 90 días), identificación de clientes en mora, seguimiento del cumplimiento de plazos y modelo de scoring para evaluar viabilidad de crédito.',
        compact: true,
        tags: ['Qlik Sense', 'MySQL', 'SQL', 'Qlik Script', 'Scoring', 'ETL'],
        stack: [],
      },
      {
        id: 'gf-kpis-comerciales',
        name: 'KPIs Comerciales y Operacionales',
        description: 'Dashboards con KPIs clave para las áreas comerciales y operacionales, con visualizaciones interactivas, filtros asociativos y plan de mejora continua sobre las aplicaciones existentes.',
        compact: true,
        tags: ['Qlik Sense', 'MySQL', 'SQL', 'Qlik Script', 'ETL'],
        stack: [],
      },
    ],
  },

  {
    id:      'hofmann',
    slug:    'hofmann',
    name:    'Droguería Hofmann SAC',
    period:  'Feb 2019 – Oct 2019',
    description: 'Analista de Software con responsabilidad integral en el ciclo de vida de cada proyecto: levantamiento de requerimientos con el cliente, diseño de la solución, desarrollo, pruebas y entrega final. Diseñé e implementé aplicaciones en QlikView y Qlik Sense para panel de control comercial, segmentación de clientes, cuadraturas de ventas y estados de resultado. Desarrollé modelos de proyección de ventas, análisis de presupuesto y control de stock de productos con Python. Responsable también de la construcción del Data Mart corporativo, la optimización de procesos ETL y la administración completa de las plataformas Qlik.',
    role:    'Analista de Software',
    location: 'Presencial - Santiago',
    achievements: [
      'Gestión autónoma de proyectos de inicio a fin: levantamiento de requerimientos, diseño, desarrollo y entrega al cliente final',
      'Desarrollo de panel de control, segmentación de clientes e indicadores de gestión comercial en Qlik Sense y QlikView',
      'Proyecciones de ventas, análisis de presupuesto y control de stock de productos mediante scripts Python',
      'Construcción de Data Mart en Qlik Sense para centralizar la extracción de datos y optimizar procesos ETL',
      'Administración de plataformas QlikView y Qlik Sense: creación de usuarios, aplicaciones y mantenimiento',
      'Capacitaciones básicas e intermedias a usuarios finales sobre herramientas BI',
    ],
    technologies: ['QlikView', 'Qlik Sense', 'Python', 'SQL Server', 'ETL', 'Data Mart', 'Pandas'],
    projects: [
      {
        id: 'hofmann-panel-comercial',
        name: 'Panel de Control y Segmentación de Clientes',
        description: 'Aplicaciones QlikView y Qlik Sense con panel de control integral, segmentación de clientes, indicadores de gestión comercial, cuadraturas de ventas y estados de resultado.',
        compact: true,
        tags: ['QlikView', 'Qlik Sense', 'SQL Server', 'Qlik Script', 'ETL'],
        stack: [],
      },
      {
        id: 'hofmann-data-mart',
        name: 'Data Mart en Qlik Sense',
        description: 'Diseño y construcción de Data Mart en Qlik Sense para centralizar la extracción de datos y optimizar los procesos ETL, mejorando consistencia y tiempos de carga.',
        compact: true,
        tags: ['Qlik Sense', 'QlikView', 'SQL Server', 'ETL', 'Data Mart'],
        stack: [],
      },
      {
        id: 'hofmann-proyecciones-python',
        name: 'Proyecciones de Ventas y Control de Presupuesto',
        description: 'Scripts Python para generación de proyecciones de ventas, análisis de presupuesto por área y control de stock de productos, automatizando el análisis de tendencias para la toma de decisiones.',
        compact: true,
        tags: ['Python', 'Pandas', 'SQL Server', 'Excel', 'Matplotlib'],
        stack: [],
      },
    ],
  },

  {
    id:      'upsociative',
    slug:    'upsociative',
    name:    'Upsociative',
    period:  'Mar 2018 – Feb 2019',
    description: 'Primer rol profesional en inteligencia de negocios, colaborando con clientes de alto perfil en sectores financiero, de pagos, gobierno y transporte público. Responsable del levantamiento de requerimientos, comprensión del negocio del cliente y entrega de soluciones BI completas con QlikView y Qlik Sense: paneles de control, segmentación de clientes, indicadores comerciales y cuadraturas de ventas. El trabajo en entornos con alta exigencia y datos sensibles fortaleció capacidades de documentación, comunicación técnica y adaptación a distintas realidades de negocio.',
    role:    'Analista de BI',
    location: 'Presencial - Santiago',
    achievements: [
      'Desarrollo de soluciones BI para clientes de sectores financiero, de pagos, gobierno y transporte público',
      'Levantamiento de requerimientos y propuesta de soluciones BI con metodologías ágiles, coordinando directamente con el cliente',
      'Desarrollo de aplicaciones QlikView y Qlik Sense: paneles de control, segmentación, indicadores comerciales y estados de resultado',
      'Documentación técnica de proyectos: levantamiento de flujos de datos, diccionario de datos y manuales de usuario',
      'Construcción de Data Mart en Qlik Sense para centralizar la extracción y mejorar procesos ETL',
      'Administración de plataformas Qlik: creación de usuarios, grupos, aplicaciones y mantenimiento general',
    ],
    technologies: ['QlikView', 'Qlik Sense', 'SQL', 'ETL', 'Data Mart', 'Scrum', 'Qlik Script'],
    projects: [
      {
        id: 'ups-panel-indicadores',
        name: 'Panel de Control e Indicadores Comerciales',
        description: 'Aplicaciones QlikView y Qlik Sense con panel de control corporativo, segmentación de clientes, indicadores comerciales, cuadraturas de ventas y estados de resultado para distintas áreas del negocio de cada cliente.',
        compact: true,
        tags: ['QlikView', 'Qlik Sense', 'SQL', 'Qlik Script', 'Scrum'],
        stack: [],
      },
      {
        id: 'ups-data-mart-admin',
        name: 'Data Mart y Administración de Plataformas Qlik',
        description: 'Construcción de Data Mart en Qlik Sense para centralizar la extracción de datos y mejorar procesos ETL, junto con administración completa de plataformas Qlik (usuarios, grupos, aplicaciones).',
        compact: true,
        tags: ['Qlik Sense', 'QlikView', 'SQL', 'ETL', 'Data Mart'],
        stack: [],
      },
      {
        id: 'ups-documentacion',
        name: 'Documentación y Entendimiento de Proyectos',
        description: 'Levantamiento y documentación de flujos de datos, diccionarios de datos, manuales de usuario y especificaciones técnicas de proyectos BI, asegurando trazabilidad y transferencia de conocimiento al cliente.',
        compact: true,
        tags: ['Documentación técnica', 'Diccionario de datos', 'Qlik Sense', 'ETL', 'Scrum'],
        stack: [],
      },
    ],
  },
];

export const COMPANY_FILTERS = [
  { key: 'all', label: 'Todas' },
  { key: 'current', label: 'Actual' },
  { key: 'cloud', label: 'Cloud' },
  { key: 'bi', label: 'BI' },
];
