/**
 * companies.js — Empresas en el CV de Nadia Zurita
 */

export const COMPANIES = [
  {
    id:      'afp-capital',
    slug:    'afp-capital',
    name:    'AFP Capital',
    period:  'Oct 2024 – Mar 2026',
    description: 'AFP Capital se separó del grupo Sura y, con eso, perdió acceso a toda la infraestructura de datos compartida. La compañía quedó sin plataforma propia. Apoyé la construcción desde cero del nuevo ecosistema de datos en GCP, alineada con los distintos departamentos que se iban formando ( Arquitectura, Gobierno de Datos, QA) desarrollando pipelines de ingesta, arquitectura Data Lakehouse en BigQuery, automatización serverless y gobierno de datos, todo en un entorno regulado por la CMF',
    role:    'Senior Data Engineer',
    location: 'Remote',
    achievements: [
      'Implementación de arquitectura Data Lakehouse de 3 capas en GCP',
      'Migración de datos maestros a través de Cloud Data Fusion',
      'Creación, levantamiento y desarrollo de procesos de datos para la visualización de Power BI (Base maestra, equipo responsable, saldos, carterización de clientes, promesa de contacto, base asesoría)',
      'Generación de POC de Dataplex para gobierno y linaje de datos',
      'Levantamiento, implementación y desarrollo de proyecto del nuevo informe previsional',
      'Desarrollo de proyecto de canal responsable para la asignación de ejecutivo a cliente',
    ],
    technologies: ['BigQuery', 'Cloud Data Fusion', 'Dataform', 'Dataproc', 'Dataplex', 'PySpark','Dataflow', 'Cloud Functions', 'Terraform', 'Python', 'SQL','Cloud Run', 'Cloud Functions', 'Cloud Storage', 'Dataproc', 'Pub/Sub', 'Cloud Scheduler', 'Dataplex', 'IAM'],
    projects: [
      {
        id: 'afp-migracion-end-to-end',
        name: 'Migración End-to-End On-Premise → GCP',
        description: 'Migración de datos desde bases de datos on-premise hacia infraestructura en GCP con validación de integridad y zero-downtime.',
        stack: [
          'Google Cloud Storage: Gestión de archivos en buckets para entornos ETL, con control de versiones y organización por ambientes (dev, qa, prod).',
          'BigQuery: Modelado de datos, creación de vistas y tablas particionadas, optimización de consultas y manejo de grandes volúmenes de datos.',
          'Cloud Data Fusion: Pipelines de ingesta y transformación desde orígenes on-premise y cloud hacia BigQuery con validación de esquemas.',
          'Cloud Dataflow: Procesamiento batch y streaming de datos con integración con Pub/Sub para ingestas de tiempo real.',
          'Cloud Functions: Funciones serverless para transformación y validación de datos en tiempo real durante la migración.',
          'Terraform: Infraestructura como código para provisionar recursos (BigQuery, Storage, cuentas de servicio, permisos IAM).',
          'Python: Scripts de migración y validación de integridad de datos.',
          'SQL: Queries de validación y reconciliación entre origen y destino.',
        ],
      },
      {
        id: 'afp-arquitectura-datos',
        name: 'Apoyo en Arquitectura de Datos',
        description: 'Diseño y evolución de la arquitectura Data Lakehouse con capas crudo, curado y producto para soportar múltiples casos de uso analíticos.',
        stack: [
          'BigQuery: Diseño de esquema dimensional, tablas de hechos y dimensiones, optimización para análisis OLAP.',
          'Dataform: Modelado modular en SQL, estructuración en capas (raw, staging, marts), control de dependencias y versionamiento con Git.',
          'Google Cloud Storage: Diseño de estructura de buckets por ambiente, retención y ciclo de vida de datos, optimización de costos.',
          'Identity and Access Management (IAM): Configuración de políticas de acceso granulares por rol y ambiente.',
          'Cloud Resource Manager: Gestión de proyectos, permisos y presupuestos de GCP.',
          'Monitoring y Logging: Implementación de alertas y dashboards de salud de la infraestructura de datos.',
        ],
      },
      {
        id: 'afp-dataform',
        name: 'Desarrollo de Dataform',
        description: '80+ modelos SQL documentados con dependencias explícitas, versionado en Git, y ejecución automática con testing integrado.',
        stack: [
          'Dataform: Desarrollo modular con SQL, definición de dependencias (ref/source), testing y documentación de columnas.',
          'Git & GitHub: Versionado de modelos, code reviews, branching strategy (main/dev), CI/CD integration.',
          'BigQuery: Compilación de SQL, ejecución de queries, optimización de performance con particionado y clustering.',
          'dbt concepts: Aunque usa Dataform, aplicación de buenas prácticas de dbt (modelado en capas, testing, documentación).',
          'YAML: Definición de configuraciones y metadatos de modelos en Dataform.',
        ],
      },
      {
        id: 'afp-consultas-programadas',
        name: 'Desarrollo de Consultas Programadas',
        description: 'Implementación de queries programadas (scheduled queries) para agregaciones diarias, actualizaciones de vistas y generación de reportes automatizados.',
        stack: [
          'BigQuery: Desarrollo y optimización de SQL complejas con window functions, subconsultas correlacionadas y CTEs.',
          'Scheduled Queries: Configuración de jobs que ejecutan automáticamente a intervalos específicos con notificaciones de error.',
          'SQL: Query optimization, índices, particionado y clustering para mejorar performance.',
          'Python: Scripts de Post-processing para transformar resultados y enviar a sistemas downstream.',
          'Cloud Pub/Sub: Integración de queries programadas con eventos de tiempo real.',
        ],
      },
      {
        id: 'afp-cloud-functions-run',
        name: 'Desarrollo de Cloud Functions & Cloud Run',
        description: 'Dos patrones complementarios de Cloud Functions en producción: pipeline batch programado para migración de fuentes on-premise y pipeline event-driven para carga de archivos con validación en tres capas, ambos con notificaciones automáticas vía SendGrid.',
        diagrams: [
          {
            id: 'cf-migracion-fuentes',
            title: 'Migración de Fuentes On-Premise con Cloud Functions',
            image: '/projects/cloud-functions-run/migracion-cf.png',
            description: 'Flujo programado diario/mensual que extrae datos desde Oracle, SQL Server y MySQL, los ingesta vía Cloud Data Fusion y aplica lógica de negocio en Cloud Functions antes de escribir en BigQuery para consumo en PowerBI y Looker.',
            steps: [
              {
                label: 'Extracción',
                detail: 'Cloud Data Fusion conecta las tres fuentes on-premise (Oracle BD, SQL Server, MySQL) y carga los datos crudos en BigQuery organizados en capas Crudo / Curado / Producto.',
              },
              {
                label: 'Orquestación',
                detail: 'Cloud Scheduler dispara las Cloud Functions según ventanas diarias y mensuales alineadas con los calendarios de corte de AFP Capital.',
              },
              {
                label: 'Lógica de negocio',
                detail: 'Cloud Functions aplica transformaciones, enriquecimiento y reglas de negocio AFP antes de entregar al procesamiento SQL final en BigQuery.',
              },
              {
                label: 'Notificaciones',
                detail: 'SendGrid envía alertas automáticas de éxito o fallo a los equipos responsables al finalizar cada carga, con detalle de registros procesados.',
              },
              {
                label: 'Consumo',
                detail: 'Los modelos certificados en BigQuery alimentan dashboards de reportería en PowerBI y Looker para los equipos de negocio.',
              },
            ],
          },
          {
            id: 'cf-carga-archivo',
            title: 'Carga de Archivo por Evento — GCS → BigQuery',
            image: '/projects/cloud-functions-run/migracion-archivo.png',
            description: 'Pipeline event-driven que se activa al detectar un archivo nuevo en Cloud Storage, ejecuta validación secuencial en tres capas dentro de la Cloud Function y finaliza con carga a BigQuery o rechazo detallado según resultado.',
            steps: [
              {
                label: 'Trigger',
                detail: 'La llegada de un archivo al bucket GCS genera un evento objeto que dispara la Cloud Function de forma automática e inmediata, sin polling.',
              },
              {
                label: 'Capa 1 — Formato y esquema',
                detail: 'Verifica que el archivo respete la estructura esperada: columnas requeridas, encoding correcto y formato de cabeceras.',
              },
              {
                label: 'Capa 2 — Tipos y nulos',
                detail: 'Controla que los tipos de dato sean los declarados y que los campos obligatorios no vengan vacíos o con valores nulos.',
              },
              {
                label: 'Capa 3 — Reglas de negocio',
                detail: 'Aplica validaciones de dominio AFP: rangos de montos válidos, RUT bien formado y fechas dentro del período de proceso vigente.',
              },
              {
                label: 'Rechazo',
                detail: 'Si falla cualquier capa: el archivo se mueve al Bucket de Fallos para auditoría y SendGrid envía un email con el detalle exacto del error.',
              },
              {
                label: 'Carga exitosa',
                detail: 'Si pasa las tres capas: inserción en la tabla BigQuery correspondiente y email de confirmación al equipo con el conteo de registros cargados.',
              },
            ],
          },
        ],
        stack: [
          'Cloud Functions: Funciones serverless en Python para ETL triggers, transformaciones de datos y validaciones en tres capas (formato, tipos, reglas de negocio).',
          'Cloud Run: Contenedores Docker con endpoints REST para microservicios de data processing con escalado automático según demanda.',
          'Cloud Data Fusion: Pipelines de ingesta desde Oracle, SQL Server y MySQL hacia BigQuery con control de esquemas y transformaciones visuales.',
          'Cloud Scheduler: Orquestación de disparos diarios y mensuales de Cloud Functions según calendarios de corte AFP.',
          'Cloud Storage: Bucket de entrada para archivos y bucket de fallos para archivos rechazados, con eventos objeto como triggers.',
          'BigQuery: Destino final de los datos procesados, organizado en capas Crudo/Curado/Producto con procesamiento SQL post-carga.',
          'SendGrid: Notificaciones automáticas de éxito, fallo y detalle de rechazo a los equipos responsables tras cada ejecución.',
          'Python: Lógica de negocio, librerías google-cloud-bigquery, pandas y sendgrid para transformación, validación y notificación.',
          'IAM & Service Accounts: Autenticación y autorización granular para el acceso de Cloud Functions a BigQuery y Cloud Storage.',
        ],
      },
      {
        id: 'afp-gobierno-datos-dataplex',
        name: 'Gobierno de Datos con Dataplex',
        description: 'Diseño e implementación de arquitectura de gobierno de datos en tres capas usando Dataplex como plataforma central, con tagging automático, reglas de calidad SQL, seguridad column-level y publicación de SLAs en Looker Studio.',
        image: '/projects/gobierno-datos-dataplex/arquitectura-dataplex.png',
        architecture: {
          layers: [
            {
              name: 'Capa Crudo',
              color: 'amber',
              description: 'Recibe los datos tal cual desde Oracle y SQL Server vía Cloud Data Fusion. Dataplex aplica tagging y linaje automático desde el minuto uno.',
            },
            {
              name: 'Capa Curada',
              color: 'purple',
              description: 'Contiene toda la lógica de Data Quality: reglas SQL que validan nulos, duplicados, formatos erróneos y anomalías antes de promover el dato.',
            },
            {
              name: 'Capa Productiva',
              color: 'teal',
              description: 'Modelos certificados con IAM granular — column-level security y row-level filters para los datos sensibles de afiliados.',
            },
          ],
          realCase: 'Flujo de cotizaciones AFP: cada noche los datos de ~2M afiliados se extraen desde Oracle a GCS, pasan por reglas de Dataplex, se transforman con Dataform en BigQuery, se aplican políticas IAM por segmento y se publican los SLAs de calidad en Looker Studio. Reglas específicas: validación de RUT, monto mayor a cero, fecha dentro del período vigente y unicidad por afiliado/mes.',
          crossCuttingTools: ['Terraform (IaC para políticas Dataplex)', 'GitLab (control de versiones)', 'Cloud Scheduler (jobs nocturnos)', 'Cloud Composer / Airflow (orquestación de DAGs)'],
        },
        stack: [
          'Dataplex Lake: Contenedor con tres zonas delimitadas (Crudo, Curada, Productiva), tagging automático y linaje de assets desde ingesta.',
          'Cloud Data Fusion: Pipelines de ingesta desde Oracle y SQL Server hacia la capa Crudo en GCS.',
          'Data Quality Rules: Reglas SQL en Dataplex para validar nulos, duplicados, formatos erróneos y anomalías entre capas.',
          'Dataform: Transformación y modelado en BigQuery con dependencias explícitas entre capas curada y productiva.',
          'IAM (column-level & row-level): Políticas granulares sobre datos sensibles de afiliados — filtros por columna y por fila según segmento.',
          'Looker Studio: Dashboards de monitoreo de SLAs de calidad de datos en tiempo real.',
          'Terraform: IaC para provisionar y versionar las políticas de Dataplex, zonas y assets como código.',
          'Cloud Composer / Airflow: Orquestación de DAGs nocturnos para el flujo completo de cotizaciones.',
          'Cloud Scheduler: Triggers de jobs nocturnos de extracción y validación.',
          'GitLab: Control de versiones de reglas de calidad, configuraciones de Dataplex y DAGs.',
        ],
      },
      {
        id: 'afp-poc-generador-metadata',
        name: 'POC Generador de Metadata con IA',
        description: 'Prototipo de generación automática de metadata de negocio para las tablas migradas desde Oracle, combinando el esquema real, datos de muestra y documentación regulatoria para producir descripciones, clasificación PII y alertas de calidad sin intervención manual.',
        image: '/projects/poc_metadata/poc_metadata.png',
        realCase: {
          inputs: [
            'Esquema de tabla_cotizaciones: 127 columnas migradas desde Oracle, con nombres técnicos heredados del sistema legacy.',
            '50 filas de muestra del último trimestre: datos reales anonimizados para que el modelo detecte patrones y anomalías.',
            'Documentación regulatoria indexada: D.L. 3.500 y Circulares CMF/SVS vectorizadas para contextualizar cada campo con su obligación normativa.',
          ],
          outputs: [
            'Descripciones de negocio en español: definición de cada columna en lenguaje entendible para el equipo de negocio, sin tecnicismos de Oracle.',
            'Clasificación PII columna por columna: identifica automáticamente RUT, montos, cuentas y datos sensibles según la regulación vigente.',
            'Dominio por tabla: asigna a qué área de negocio pertenece cada tabla (Recaudación, Afiliados, Inversiones, etc.).',
            'Alertas de anomalías: detecta en la muestra valores que romperían pipelines — como los nulos encontrados en cuota_historica antes de que llegaran a producción.',
          ],
        },
        stack: [
          'Vertex AI / Gemini: Modelo de lenguaje para generar descripciones de columnas y clasificar PII a partir del esquema y documentación regulatoria.',
          'BigQuery: Fuente del esquema real (INFORMATION_SCHEMA) y extracción de muestras representativas para análisis.',
          'Cloud Storage: Almacenamiento de documentos regulatorios (D.L. 3.500, Circulares CMF/SVS) indexados para RAG.',
          'Dataplex Data Catalog: Destino de la metadata generada — tags de negocio, clasificación de sensibilidad y dominio por asset.',
          'Python: Orquestación del pipeline: extracción de esquema, llamadas a la API del modelo, validación y escritura en el catálogo.',
          'Cloud Functions: Trigger serverless para ejecutar el generador cuando se detecta una nueva tabla o cambio de esquema.',
          'RAG (Retrieval-Augmented Generation): Recuperación de fragmentos relevantes de la normativa para fundamentar cada descripción generada.',
        ],
      },
    ],
  },

  {
    id:      'elitsoft',
    slug:    'elitsoft',
    name:    'ElitSoft',
    period:  'Abr 2023 – Sep 2024',
    description: 'Orquestación de pipelines AWS con Apache Airflow y arquitectura de CI/CD para data.',
    role:    'Data Engineer',
    location: 'Remote',
    achievements: [
      'Automatización del 100% de ingestas batch desde legacy a Redshift',
      'Reducción del 60% en tiempo de procesamiento con Spark en EMR',
      'Implementación de CI/CD con AWS CodePipeline y Jenkins',
      'Cero intervenciones manuales en producción por 6 meses consecutivos',
    ],
    technologies: ['AWS Glue', 'Amazon EMR', 'Apache Airflow', 'Redshift', 'Lambda', 'CodePipeline'],
    projects: [
      {
        id: 'elitsoft-automatizacion-ingestas',
        name: 'Automatización de Ingestas Batch Legacy → Redshift',
        description: 'Automatización del 100% de ingestas batch desde sistemas legacy a Redshift mediante DAGs en Airflow con validación de integridad y monitoreo.',
        stack: [
          'AWS Glue: Catálogo de datos, descubrimiento de esquemas, transformación ETL serverless para ingestas desde múltiples orígenes.',
          'Apache Airflow: Orquestación de DAGs para scheduling de ingestas, manejo de dependencias, reintentos y alertas de fallos.',
          'Redshift: Data warehouse, materialización de tablas, optimización con distkeys y sortkeys, gestión de concurrencia.',
          'AWS Lambda: Funciones serverless para transformaciones ligeras, validación de datos y notificaciones.',
          'S3: Almacenamiento intermedio de archivos, staging tables para ingestas incrementales.',
          'CloudWatch: Monitoreo de jobs, logs centralizados, alertas y dashboards de performance.',
          'Python: Desarrollo de DAGs, custom operators, transformaciones de datos, validaciones.',
          'SQL: Queries de transformación, reconciliación entre origen y destino, agregaciones finales.',
        ],
      },
      {
        id: 'elitsoft-spark-emr',
        name: 'Optimización de Spark en Amazon EMR',
        description: 'Reducción del 60% en tiempo de procesamiento mediante tuning de configuraciones de Spark, particionado de datos y optimización de memoria.',
        stack: [
          'Amazon EMR: Cluster management, versioning de Spark, configuración de executors y drivers para máximo performance.',
          'Apache Spark: Optimización de stage execution, lazy evaluation, particionado de DataFrames, cache strategies.',
          'PySpark: Desarrollo de jobs de transformación con optimizaciones de performance (broadcast joins, columnar storage).',
          'S3: Lectura/escritura optimizada, particionado de datos por fecha/región para scan reduction.',
          'YARN: Resource management, memory allocation, job scheduling y monitoring.',
          'CloudWatch: Metrics de cluster, CPU/Memory utilization, job duration tracking.',
          'SQL: Queries distribuidas en Spark SQL, predicate pushdown, columnar formats (Parquet).',
        ],
      },
      {
        id: 'elitsoft-cicd-pipeline',
        name: 'CI/CD Pipeline con AWS CodePipeline y Jenkins',
        description: 'Implementación de pipeline end-to-end para automatización de builds, tests y deployments de código de data en múltiples ambientes.',
        stack: [
          'AWS CodePipeline: Orquestación de stages (source, build, test, deploy), integración con Git, manual approvals.',
          'Jenkins: Ejecución de builds, tests unitarios, código estático, deployment a ambientes (dev, qa, prod).',
          'AWS CodeBuild: Compilación y testing de código Python, instalación de dependencias, unit tests.',
          'GitHub/GitLab: Repositorio de código, webhooks para trigger de pipelines, pull request reviews.',
          'Docker: Containerización de DAGs y jobs Spark para reproducibilidad en distintos ambientes.',
          'Terraform: IaC para provisionar infraestructura (clusters, jobs, buckets) desde código.',
          'pytest: Framework de testing para validar lógica de transformación de datos.',
          'CloudFormation: Declaración de infraestructura como código para ambientes de dev/qa/prod.',
        ],
      },
      {
        id: 'elitsoft-dags-airflow',
        name: 'Desarrollo de DAGs Orchestración en Airflow',
        description: 'Diseño de DAGs resilientes con manejo de errores, reintentos inteligentes, y monitoreo centralizado para 50+ pipelines diarios.',
        stack: [
          'Apache Airflow: DAG definitions, custom operators, sensors, XComs para comunicación entre tareas, SLA policies.',
          'Python: Desarrollo de DAGs, custom hooks y operators, lógica de transformación, error handling.',
          'AWS Airflow Managed Workflows: Managed service con auto-scaling, monitoring integrado, seguridad enterprise.',
          'Redshift: Conexiones de destino, inserción de datos, queries de validación post-ingesta.',
          'S3: Staging de archivos, logging de ejecuciones, backups de metadatos.',
          'Email/Slack: Notificaciones de fallo, alertas de SLA breaches, reportes diarios.',
          'SQL: Queries de transformación ejecutadas dentro de DAGs, validación de datos.',
        ],
      },
      {
        id: 'elitsoft-infraestructura-aws',
        name: 'Infraestructura AWS para Data Pipelines',
        description: 'Diseño de arquitectura serverless y escalable para pipelines de datos con alta disponibilidad, disaster recovery y optimización de costos.',
        stack: [
          'Terraform: IaC para provisionar Redshift, Glue, Airflow, EMR, IAM roles, security groups y VPCs.',
          'AWS VPC: Configuración de subnets, security groups, endpoints para acceso privado a servicios.',
          'IAM: Gestión de roles y políticas granulares para cada componente (Glue, Airflow, Lambda).',
          'CloudWatch: Monitoreo centralizado, logs, métricas, dashboards y alarmas customizadas.',
          'AWS Secrets Manager: Gestión segura de credenciales de bases de datos y APIs.',
          'AWS S3: Bucket policies, versioning, lifecycle rules, encryption at rest y in transit.',
          'AWS Backup: Snapshots automáticos de Redshift, replicación a otra región para DR.',
        ],
      },
    ],
  },

  {
    id:      'cic-sa',
    slug:    'cic-sa',
    name:    'CIC S.A.',
    period:  'Mar 2020 – Abr 2023',
    description: 'Dashboards de logística en tiempo real y transformación de reportes manuales a automatizados.',
    role:    'BI Developer / Data Analyst',
    location: 'Presencial - Santiago',
    achievements: [
      'Desarrollo de dashboard logístico con actualización cada 15 minutos en Qlik Sense',
      'Reducción del tiempo de reporte de 2 días a tiempo real',
      'Adopción del 100% del área logística en el nuevo sistema',
      'Automatización de ETL con Control-M y Oracle',
    ],
    technologies: ['Qlik Sense', 'QlikView', 'NPrinting', 'Oracle', 'Control-M', 'SQL'],
    projects: [
      {
        id: 'cic-dashboard-logistico',
        name: 'Dashboard Logístico Real-Time en Qlik Sense',
        description: 'Dashboard interactivo con actualización cada 15 minutos mostrando KPIs de logística, inventario y despachos con drilldown a nivel de detalle de transacciones.',
        stack: [
          'Qlik Sense: Aplicación interactiva, visualizaciones (tablas, gráficos, KPIs), filtros asociativos, drill-down capabilities.',
          'Oracle: Base de datos de origen, queries optimizadas, vistas materializadas para performance de dashboard.',
          'ETL Control-M: Scheduling de ingestas cada 15 minutos, validación de datos, alertas de anomalías.',
          'Qlik Script: Carga de datos en memoria, transformaciones en script (dimensiones derivadas, agregaciones).',
          'Grafana/Kibana: Monitoreo del performance del dashboard, alertas de latencia excesiva.',
          'NPrinting: Reportes programados en PDF/Excel derivados del dashboard, distribución a stakeholders.',
          'SQL: Queries analíticos en Oracle, optimización de índices para consultas del dashboard.',
        ],
      },
      {
        id: 'cic-migracion-qlikview-sense',
        name: 'Migración de QlikView a Qlik Sense',
        description: 'Migración de aplicaciones legacy en QlikView a la plataforma moderna Qlik Sense manteniendo funcionalidad y mejorando experiencia de usuario.',
        stack: [
          'QlikView: Lectura de aplicaciones legacy (.qvw), extracción de scripts, análisis de dependencias.',
          'Qlik Sense: Rediseño de dashboards con nuevas visualizaciones, mejor UX, optimización de performance.',
          'Qlik Migration Manager: Herramienta para migración automática de elementos, mapping de datos.',
          'Qlik Script: Reescritura de scripts de transformación para nueva arquitectura, optimizaciones.',
          'Oracle SQL: Queries de origen, creación de nuevas vistas para soportar nuevas métricas.',
          'NPrinting: Migración de reportes QlikView a reportes Sense con nuevos templates.',
          'Git: Versionado de scripts de transformación y configuraciones de Qlik.',
        ],
      },
      {
        id: 'cic-automatizacion-reportes',
        name: 'Automatización de Reportes con NPrinting',
        description: 'Sistema de generación y distribución automática de reportes en PDF, Excel y email hacia más de 50 usuarios ejecutivos diarios.',
        stack: [
          'NPrinting: Diseño de templates de reportes, scheduling automático, distribución por email/SharePoint.',
          'Qlik Sense: Conexión a aplicaciones Sense, exportación de datos, integración de visualizaciones en reportes.',
          'Crystal Reports: Diseño de reportes complejos con subreportes, agrupamientos, totalizaciones.',
          'SQL: Queries analíticas para extracción de datos base de reportes, agregaciones dinámicas.',
          'Email: Integración SMTP para distribución automática de reportes según schedule.',
          'SharePoint: Almacenamiento centralizado de reportes archivados, versioning.',
          'Control-M: Scheduling de ejecuciones de reportes, notificaciones de éxito/fallo.',
        ],
      },
      {
        id: 'cic-etl-oracle-controlm',
        name: 'ETL Automatizado Oracle + Control-M',
        description: 'Pipeline ETL completo que ingesta datos de múltiples tablas Oracle, aplica transformaciones de negocio y carga en data warehouse de Qlik cada 6 horas.',
        stack: [
          'Control-M: Orquestación de jobs ETL, scheduling con dependencias, alertas y notificaciones.',
          'Oracle: Base de datos de origen, views para staging, conexiones con librerías ODBC.',
          'SQL Developer: Desarrollo de queries complejas, procedures y functions para transformaciones.',
          'Script Shell/Batch: Scripts de extracción, carga incremental, validación de integridad.',
          'Python: Scripts de transformación de datos, validaciones customizadas, manejo de excepciones.',
          'Archivos Flat: Stagings intermedios, archivos de control para rastreo de ejecutaciones.',
          'Qlik Script: Carga de datos transformados en aplicaciones Qlik, optimizaciones en memoria.',
        ],
      },
      {
        id: 'cic-analisis-datos-logistica',
        name: 'Análisis de Datos y Métricas Logísticas',
        description: 'Desarrollo de análisis exploratorio, KPIs de operación y modelos analíticos para optimización de procesos logísticos y decisiones ejecutivas.',
        stack: [
          'SQL: Queries analíticas complejas, window functions, CTEs, particionado dinámico de datos.',
          'Qlik Sense: Dimensiones derivadas, expresiones analíticas avanzadas, Sets y variables.',
          'Excel/Power Query: Análisis ad-hoc, modelos financieros, forecasting de demanda.',
          'Tableau (opcional): Visualizaciones adicionales, dashboards de tendencias y anomalías.',
          'Python/Pandas: Análisis estadístico, detección de outliers, análisis de correlaciones.',
          'Business Intelligence: Definición de KPIs, SLAs operacionales, métricas de control.',
          'Presentación: Dashboards ejecutivos, reportes de tendencias, recomendaciones de optimización.',
        ],
      },
    ],
  },
];

export const COMPANY_FILTERS = [
  { key: 'all', label: 'Todas' },
  { key: 'current', label: 'Actual' },
  { key: 'cloud', label: 'Cloud' },
  { key: 'bi', label: 'BI' },
];
