/**
 * companies.js — Empresas en el CV de Nadia Zurita
 */

export const COMPANIES = [
  {
    id:      'afp-capital',
    slug:    'afp-capital',
    name:    'AFP Capital',
    period:  'Oct 2024 – Mar 2026',
    description: 'Migración a arquitectura Data Lakehouse en GCP con gobierno de datos y pipelines automatizados.',
    role:    'Senior Data Engineer',
    location: 'Remote',
    achievements: [
      'Implementación de arquitectura Data Lakehouse de 3 capas en GCP',
      'Migración de datos maestros a través de Cloud Data Fusion',
      'Creación, levantamiento y desarrollo de procesos de datos para la visualización de Power BI (Base maestra, equipo responsable, saldos, carterización de clientes, promesa de contacto, base asesoría)',
      'Generación de POC de Dataplex para gobierno y linaje de datos',
      'Levantamiento, implementación y desarrollo de proyecto del nuevo informe previsional',
      'Desarrollo de proyecto de canal responsable para la asignación de ejecutivo a cliente',
    ],
    technologies: ['BigQuery', 'Cloud Data Fusion', 'Dataform', 'Dataproc', 'Dataplex', 'PySpark','Dataflow', 'Cloud Functions', 'Terraform', 'Python', 'SQL','Cloud Run', 'Cloud Functions', 'Cloud Storage', 'Dataproc', 'Pub/Sub', 'Cloud Scheduler', 'Dataplex', 'IAM'],
    projects: [
      {
        id: 'afp-migracion-end-to-end',
        name: 'Migración End-to-End On-Premise → GCP',
        description: 'Migración de datos desde bases de datos on-premise hacia infraestructura en GCP con validación de integridad y zero-downtime.',
        stack: [
          'Google Cloud Storage: Gestión de archivos en buckets para entornos ETL, con control de versiones y organización por ambientes (dev, qa, prod).',
          'BigQuery: Modelado de datos, creación de vistas y tablas particionadas, optimización de consultas y manejo de grandes volúmenes de datos.',
          'Cloud Data Fusion: Pipelines de ingesta y transformación desde orígenes on-premise y cloud hacia BigQuery con validación de esquemas.',
          'Cloud Dataflow: Procesamiento batch y streaming de datos con integración con Pub/Sub para ingestas de tiempo real.',
          'Cloud Functions: Funciones serverless para transformación y validación de datos en tiempo real durante la migración.',
          'Terraform: Infraestructura como código para provisionar recursos (BigQuery, Storage, cuentas de servicio, permisos IAM).',
          'Python: Scripts de migración y validación de integridad de datos.',
          'SQL: Queries de validación y reconciliación entre origen y destino.',
        ],
      },
      {
        id: 'afp-arquitectura-datos',
        name: 'Apoyo en Arquitectura de Datos',
        description: 'Diseño y evolución de la arquitectura Data Lakehouse con capas crudo, curado y producto para soportar múltiples casos de uso analíticos.',
        stack: [
          'BigQuery: Diseño de esquema dimensional, tablas de hechos y dimensiones, optimización para análisis OLAP.',
          'Dataform: Modelado modular en SQL, estructuración en capas (raw, staging, marts), control de dependencias y versionamiento con Git.',
          'Google Cloud Storage: Diseño de estructura de buckets por ambiente, retención y ciclo de vida de datos, optimización de costos.',
          'Identity and Access Management (IAM): Configuración de políticas de acceso granulares por rol y ambiente.',
          'Cloud Resource Manager: Gestión de proyectos, permisos y presupuestos de GCP.',
          'Monitoring y Logging: Implementación de alertas y dashboards de salud de la infraestructura de datos.',
        ],
      },
      {
        id: 'afp-dataform',
        name: 'Desarrollo de Dataform',
        description: '80+ modelos SQL documentados con dependencias explícitas, versionado en Git, y ejecución automática con testing integrado.',
        stack: [
          'Dataform: Desarrollo modular con SQL, definición de dependencias (ref/source), testing y documentación de columnas.',
          'Git & GitHub: Versionado de modelos, code reviews, branching strategy (main/dev), CI/CD integration.',
          'BigQuery: Compilación de SQL, ejecución de queries, optimización de performance con particionado y clustering.',
          'dbt concepts: Aunque usa Dataform, aplicación de buenas prácticas de dbt (modelado en capas, testing, documentación).',
          'YAML: Definición de configuraciones y metadatos de modelos en Dataform.',
        ],
      },
      {
        id: 'afp-consultas-programadas',
        name: 'Desarrollo de Consultas Programadas',
        description: 'Implementación de queries programadas (scheduled queries) para agregaciones diarias, actualizaciones de vistas y generación de reportes automatizados.',
        stack: [
          'BigQuery: Desarrollo y optimización de SQL complejas con window functions, subconsultas correlacionadas y CTEs.',
          'Scheduled Queries: Configuración de jobs que ejecutan automáticamente a intervalos específicos con notificaciones de error.',
          'SQL: Query optimization, índices, particionado y clustering para mejorar performance.',
          'Python: Scripts de Post-processing para transformar resultados y enviar a sistemas downstream.',
          'Cloud Pub/Sub: Integración de queries programadas con eventos de tiempo real.',
        ],
      },
      {
        id: 'afp-cloud-functions-run',
        name: 'Desarrollo de Cloud Functions & Cloud Run',
        description: 'Microservicios serverless para transformación, validación y orquestación de datos con escalado automático.',
        stack: [
          'Cloud Functions: Funciones serverless en Python/Node.js para ETL triggers, transformaciones de datos, validaciones.',
          'Cloud Run: Contenedores Docker con endpoints REST para microservicios de data processing, escalado automático según demanda.',
          'Python: Desarrollo de lógica de negocio, librerías (pandas, google-cloud-bigquery, requests).',
          'Docker: Containerización de aplicaciones para Cloud Run.',
          'Cloud Tasks: Encola y ejecuta tareas asincrónicas (reintentos, deadletter queues).',
          'Cloud Pub/Sub: Comunicación event-driven entre funciones y servicios.',
          'IAM & Service Accounts: Autenticación y autorización para acceso a BigQuery y Storage.',
        ],
      },
      {
        id: 'afp-gobierno-datos-dataplex',
        name: 'Gobierno de Datos con Dataplex',
        description: 'Implementación de catálogo de datos, linaje, calidad de datos y políticas de acceso con Dataplex.',
        stack: [
          'Dataplex: Catálogo de datos (Data Catalog), definición de zonas de datos, Asset tagging y linaje automático.',
          'Data Quality: Reglas para detectar nulos, duplicados, formatos erróneos y anomalías previo a la carga en capas productivas.',
          'Looker Studio: Dashboards de calidad de datos en tiempo real, monitoreo de SLAs de data.',
          'BigQuery Metadata: Extracción de metadatos y linaje automático desde queries ejecutadas.',
          'IAM Policies: Implementación de políticas de acceso granulares a nivel de datos sensibles.',
          'Terraform: IaC para provisionar políticas de Dataplex y configuraciones de gobierno.',
          'SQL: Queries de validación de calidad y generación de reportes de linaje.',
        ],
      },
    ],
  },

  {
    id:      'elitsoft',
    slug:    'elitsoft',
    name:    'ElitSoft',
    period:  'Abr 2023 – Sep 2024',
    description: 'Orquestación de pipelines AWS con Apache Airflow y arquitectura de CI/CD para data.',
    role:    'Data Engineer',
    location: 'Remote',
    achievements: [
      'Automatización del 100% de ingestas batch desde legacy a Redshift',
      'Reducción del 60% en tiempo de procesamiento con Spark en EMR',
      'Implementación de CI/CD con AWS CodePipeline y Jenkins',
      'Cero intervenciones manuales en producción por 6 meses consecutivos',
    ],
    technologies: ['AWS Glue', 'Amazon EMR', 'Apache Airflow', 'Redshift', 'Lambda', 'CodePipeline'],
    projects: [
      {
        id: 'elitsoft-automatizacion-ingestas',
        name: 'Automatización de Ingestas Batch Legacy → Redshift',
        description: 'Automatización del 100% de ingestas batch desde sistemas legacy a Redshift mediante DAGs en Airflow con validación de integridad y monitoreo.',
        stack: [
          'AWS Glue: Catálogo de datos, descubrimiento de esquemas, transformación ETL serverless para ingestas desde múltiples orígenes.',
          'Apache Airflow: Orquestación de DAGs para scheduling de ingestas, manejo de dependencias, reintentos y alertas de fallos.',
          'Redshift: Data warehouse, materialización de tablas, optimización con distkeys y sortkeys, gestión de concurrencia.',
          'AWS Lambda: Funciones serverless para transformaciones ligeras, validación de datos y notificaciones.',
          'S3: Almacenamiento intermedio de archivos, staging tables para ingestas incrementales.',
          'CloudWatch: Monitoreo de jobs, logs centralizados, alertas y dashboards de performance.',
          'Python: Desarrollo de DAGs, custom operators, transformaciones de datos, validaciones.',
          'SQL: Queries de transformación, reconciliación entre origen y destino, agregaciones finales.',
        ],
      },
      {
        id: 'elitsoft-spark-emr',
        name: 'Optimización de Spark en Amazon EMR',
        description: 'Reducción del 60% en tiempo de procesamiento mediante tuning de configuraciones de Spark, particionado de datos y optimización de memoria.',
        stack: [
          'Amazon EMR: Cluster management, versioning de Spark, configuración de executors y drivers para máximo performance.',
          'Apache Spark: Optimización de stage execution, lazy evaluation, particionado de DataFrames, cache strategies.',
          'PySpark: Desarrollo de jobs de transformación con optimizaciones de performance (broadcast joins, columnar storage).',
          'S3: Lectura/escritura optimizada, particionado de datos por fecha/región para scan reduction.',
          'YARN: Resource management, memory allocation, job scheduling y monitoring.',
          'CloudWatch: Metrics de cluster, CPU/Memory utilization, job duration tracking.',
          'SQL: Queries distribuidas en Spark SQL, predicate pushdown, columnar formats (Parquet).',
        ],
      },
      {
        id: 'elitsoft-cicd-pipeline',
        name: 'CI/CD Pipeline con AWS CodePipeline y Jenkins',
        description: 'Implementación de pipeline end-to-end para automatización de builds, tests y deployments de código de data en múltiples ambientes.',
        stack: [
          'AWS CodePipeline: Orquestación de stages (source, build, test, deploy), integración con Git, manual approvals.',
          'Jenkins: Ejecución de builds, tests unitarios, código estático, deployment a ambientes (dev, qa, prod).',
          'AWS CodeBuild: Compilación y testing de código Python, instalación de dependencias, unit tests.',
          'GitHub/GitLab: Repositorio de código, webhooks para trigger de pipelines, pull request reviews.',
          'Docker: Containerización de DAGs y jobs Spark para reproducibilidad en distintos ambientes.',
          'Terraform: IaC para provisionar infraestructura (clusters, jobs, buckets) desde código.',
          'pytest: Framework de testing para validar lógica de transformación de datos.',
          'CloudFormation: Declaración de infraestructura como código para ambientes de dev/qa/prod.',
        ],
      },
      {
        id: 'elitsoft-dags-airflow',
        name: 'Desarrollo de DAGs Orchestración en Airflow',
        description: 'Diseño de DAGs resilientes con manejo de errores, reintentos inteligentes, y monitoreo centralizado para 50+ pipelines diarios.',
        stack: [
          'Apache Airflow: DAG definitions, custom operators, sensors, XComs para comunicación entre tareas, SLA policies.',
          'Python: Desarrollo de DAGs, custom hooks y operators, lógica de transformación, error handling.',
          'AWS Airflow Managed Workflows: Managed service con auto-scaling, monitoring integrado, seguridad enterprise.',
          'Redshift: Conexiones de destino, inserción de datos, queries de validación post-ingesta.',
          'S3: Staging de archivos, logging de ejecuciones, backups de metadatos.',
          'Email/Slack: Notificaciones de fallo, alertas de SLA breaches, reportes diarios.',
          'SQL: Queries de transformación ejecutadas dentro de DAGs, validación de datos.',
        ],
      },
      {
        id: 'elitsoft-infraestructura-aws',
        name: 'Infraestructura AWS para Data Pipelines',
        description: 'Diseño de arquitectura serverless y escalable para pipelines de datos con alta disponibilidad, disaster recovery y optimización de costos.',
        stack: [
          'Terraform: IaC para provisionar Redshift, Glue, Airflow, EMR, IAM roles, security groups y VPCs.',
          'AWS VPC: Configuración de subnets, security groups, endpoints para acceso privado a servicios.',
          'IAM: Gestión de roles y políticas granulares para cada componente (Glue, Airflow, Lambda).',
          'CloudWatch: Monitoreo centralizado, logs, métricas, dashboards y alarmas customizadas.',
          'AWS Secrets Manager: Gestión segura de credenciales de bases de datos y APIs.',
          'AWS S3: Bucket policies, versioning, lifecycle rules, encryption at rest y in transit.',
          'AWS Backup: Snapshots automáticos de Redshift, replicación a otra región para DR.',
        ],
      },
    ],
  },

  {
    id:      'cic-sa',
    slug:    'cic-sa',
    name:    'CIC S.A.',
    period:  'Mar 2020 – Abr 2023',
    description: 'Dashboards de logística en tiempo real y transformación de reportes manuales a automatizados.',
    role:    'BI Developer / Data Analyst',
    location: 'Presencial - Santiago',
    achievements: [
      'Desarrollo de dashboard logístico con actualización cada 15 minutos en Qlik Sense',
      'Reducción del tiempo de reporte de 2 días a tiempo real',
      'Adopción del 100% del área logística en el nuevo sistema',
      'Automatización de ETL con Control-M y Oracle',
    ],
    technologies: ['Qlik Sense', 'QlikView', 'NPrinting', 'Oracle', 'Control-M', 'SQL'],
    projects: [
      {
        id: 'cic-dashboard-logistico',
        name: 'Dashboard Logístico Real-Time en Qlik Sense',
        description: 'Dashboard interactivo con actualización cada 15 minutos mostrando KPIs de logística, inventario y despachos con drilldown a nivel de detalle de transacciones.',
        stack: [
          'Qlik Sense: Aplicación interactiva, visualizaciones (tablas, gráficos, KPIs), filtros asociativos, drill-down capabilities.',
          'Oracle: Base de datos de origen, queries optimizadas, vistas materializadas para performance de dashboard.',
          'ETL Control-M: Scheduling de ingestas cada 15 minutos, validación de datos, alertas de anomalías.',
          'Qlik Script: Carga de datos en memoria, transformaciones en script (dimensiones derivadas, agregaciones).',
          'Grafana/Kibana: Monitoreo del performance del dashboard, alertas de latencia excesiva.',
          'NPrinting: Reportes programados en PDF/Excel derivados del dashboard, distribución a stakeholders.',
          'SQL: Queries analíticos en Oracle, optimización de índices para consultas del dashboard.',
        ],
      },
      {
        id: 'cic-migracion-qlikview-sense',
        name: 'Migración de QlikView a Qlik Sense',
        description: 'Migración de aplicaciones legacy en QlikView a la plataforma moderna Qlik Sense manteniendo funcionalidad y mejorando experiencia de usuario.',
        stack: [
          'QlikView: Lectura de aplicaciones legacy (.qvw), extracción de scripts, análisis de dependencias.',
          'Qlik Sense: Rediseño de dashboards con nuevas visualizaciones, mejor UX, optimización de performance.',
          'Qlik Migration Manager: Herramienta para migración automática de elementos, mapping de datos.',
          'Qlik Script: Reescritura de scripts de transformación para nueva arquitectura, optimizaciones.',
          'Oracle SQL: Queries de origen, creación de nuevas vistas para soportar nuevas métricas.',
          'NPrinting: Migración de reportes QlikView a reportes Sense con nuevos templates.',
          'Git: Versionado de scripts de transformación y configuraciones de Qlik.',
        ],
      },
      {
        id: 'cic-automatizacion-reportes',
        name: 'Automatización de Reportes con NPrinting',
        description: 'Sistema de generación y distribución automática de reportes en PDF, Excel y email hacia más de 50 usuarios ejecutivos diarios.',
        stack: [
          'NPrinting: Diseño de templates de reportes, scheduling automático, distribución por email/SharePoint.',
          'Qlik Sense: Conexión a aplicaciones Sense, exportación de datos, integración de visualizaciones en reportes.',
          'Crystal Reports: Diseño de reportes complejos con subreportes, agrupamientos, totalizaciones.',
          'SQL: Queries analíticas para extracción de datos base de reportes, agregaciones dinámicas.',
          'Email: Integración SMTP para distribución automática de reportes según schedule.',
          'SharePoint: Almacenamiento centralizado de reportes archivados, versioning.',
          'Control-M: Scheduling de ejecuciones de reportes, notificaciones de éxito/fallo.',
        ],
      },
      {
        id: 'cic-etl-oracle-controlm',
        name: 'ETL Automatizado Oracle + Control-M',
        description: 'Pipeline ETL completo que ingesta datos de múltiples tablas Oracle, aplica transformaciones de negocio y carga en data warehouse de Qlik cada 6 horas.',
        stack: [
          'Control-M: Orquestación de jobs ETL, scheduling con dependencias, alertas y notificaciones.',
          'Oracle: Base de datos de origen, views para staging, conexiones con librerías ODBC.',
          'SQL Developer: Desarrollo de queries complejas, procedures y functions para transformaciones.',
          'Script Shell/Batch: Scripts de extracción, carga incremental, validación de integridad.',
          'Python: Scripts de transformación de datos, validaciones customizadas, manejo de excepciones.',
          'Archivos Flat: Stagings intermedios, archivos de control para rastreo de ejecutaciones.',
          'Qlik Script: Carga de datos transformados en aplicaciones Qlik, optimizaciones en memoria.',
        ],
      },
      {
        id: 'cic-analisis-datos-logistica',
        name: 'Análisis de Datos y Métricas Logísticas',
        description: 'Desarrollo de análisis exploratorio, KPIs de operación y modelos analíticos para optimización de procesos logísticos y decisiones ejecutivas.',
        stack: [
          'SQL: Queries analíticas complejas, window functions, CTEs, particionado dinámico de datos.',
          'Qlik Sense: Dimensiones derivadas, expresiones analíticas avanzadas, Sets y variables.',
          'Excel/Power Query: Análisis ad-hoc, modelos financieros, forecasting de demanda.',
          'Tableau (opcional): Visualizaciones adicionales, dashboards de tendencias y anomalías.',
          'Python/Pandas: Análisis estadístico, detección de outliers, análisis de correlaciones.',
          'Business Intelligence: Definición de KPIs, SLAs operacionales, métricas de control.',
          'Presentación: Dashboards ejecutivos, reportes de tendencias, recomendaciones de optimización.',
        ],
      },
    ],
  },
];

export const COMPANY_FILTERS = [
  { key: 'all', label: 'Todas' },
  { key: 'current', label: 'Actual' },
  { key: 'cloud', label: 'Cloud' },
  { key: 'bi', label: 'BI' },
];
